### ISSUE TITLE
WAIC-TEST-0020-01

### ISSUE THREAD

**Issue by cocktailz** [waic/as_testfile2015#3]
WAIC-TEST-0020-01
https://github.com/waic/as_testfile2015/blob/dev/WAIC-TEST/HTML/WAIC-TEST-0020-01.txt

select 要素とobject 要素についてのテストです。
object 要素を選択しただけで実行されるのではなく、ユーザーが実行ボタンを押して初めて実行するようになるかどうかを調べるテストです。

**Comment by nishimotz** [comment]
NVDA （日本語ベータ版）+ Windows 10 + (Firefox 54 / IE / Edge) で確認して、
特にテストそのものについての問題はないと思います。
また支援技術側の動作にも問題はなさそうでした。

**Comment by cocktailz** [comment]
Alt + 上下矢印キーで選択すると、Altキーを再度押すまでonChangeは作動しないものが多い。
痛い目に合ってるかどうか、痛い目に合ってることに気づいているかどうか。

**Comment by cocktailz** [comment]
H84のテストコードはHTMLのみ使用したものであり、JavaScriptを使わないことが前提の達成方法になっている。
WAIC-TEST-0020-01は削除し、SCR19のテストファイルを作成するときに改めて議論する。
